name: "🎃 Bug Report"
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: General description of the problem. Add screenshots if needed.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the problem.
      placeholder: |
        1. Open ....
        2. Click on ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info (Optional)
      description: Operating system and Firefox version, if relevant.
      placeholder: |
        Firefox version: 
        Operating system:
