name: "✨ Feature Request"
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear explanation of the feature and how it should work. Add screenshots if needed.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info (Optional)
      description: Operating system and Firefox version, if relevant.
      placeholder: |
        Firefox version: 
        Operating system:
